name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for TemaProject1
      run: dotnet restore ./TemaProject1/TemaProject1.csproj

    - name: Restore dependencies for TestProject
      run: dotnet restore ./TestProject/TestProject.csproj

    - name: Build TemaProject1
      run: dotnet build ./TemaProject1/TemaProject1.csproj --no-restore

    - name: Build TestProject
      run: dotnet build ./TestProject/TestProject.csproj --no-restore

    - name: Test TestProject
      run: dotnet test ./TestProject/TestProject.csproj --no-build --verbosity normal
    
  create-and-merge-pr:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated changes from dev"
          title: "Automated PR from Dev to Main"
          body: "This is an automated pull request to update the main branch with the latest changes from dev."
          base: "main"
          branch: "update-main-from-dev-${{ github.run_id }}"
          labels: "auto-merge"
      
      - name: Auto Merge
        if: steps.create-pr.outputs.pull-request-number
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          mergeMethod: merge
          pullRequestLabels: "auto-merge"
          pullRequestLabels: "automerge"
