name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for TemaProject1
      run: dotnet restore ./TemaProject1/TemaProject1.csproj

    - name: Restore dependencies for TestProject
      run: dotnet restore ./TestProject/TestProject.csproj

    - name: Build TemaProject1
      run: dotnet build ./TemaProject1/TemaProject1.csproj --no-restore

    - name: Build TestProject
      run: dotnet build ./TestProject/TestProject.csproj --no-restore

    - name: Test TestProject
      run: dotnet test ./TestProject/TestProject.csproj --no-build --verbosity normal
    
    - uses: actions/checkout@v4
    
    - name: Create Pull Request
      if: success()
      uses: "pascalgn/automerge-action@v0.16.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: "Automated changes from dev"
        title: "Merge changes from dev to main"
        body: "This is an automated pull request to merge changes from the dev branch to the main branch."
        base: "main" 
        branch: "dev-to-main-merge" 
