name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for TemaProject1
      run: dotnet restore ./TemaProject/TemaProject.csproj

    - name: Restore dependencies for TestProject
      run: dotnet restore ./TestProject/TestProject.csproj

    - name: Build TemaProject1
      run: dotnet build ./TemaProject/TemaProject.csproj --no-restore

    - name: Build TestProject
      run: dotnet build ./TestProject/TestProject.csproj --no-restore

    - name: Test TestProject
      run: dotnet test ./TestProject/TestProject.csproj --no-build --verbosity normal
