name: .NET CI/CD Workflow

on:
  push:
    branches: [ dev1 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore ./TemaProject1/TemaProject1.csproj
        dotnet restore ./TestProject/TestProject.csproj

    - name: Build projects
      run: |
        dotnet build ./TemaProject1/TemaProject1.csproj --no-restore
        dotnet build ./TestProject/TestProject.csproj --no-restore

    - name: Run tests
      run: dotnet test ./TestProject/TestProject.csproj --no-build --verbosity normal

    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        commit-message: "Automated changes from dev"
        title: "Automatikus PR: Dev -> Main"
        body: "Ez egy automatikusan generált pull request a `dev` branch változásainak a `main` branch-be való merge-eléséhez."
        base: "main"  
        branch: "dev"  
        delete-branch: false 
